services: 
  postgres:
    image: postgres:16
    container_name: exness-postgres
    ports: 
      - "5436:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: exness:db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: exness-redis
    ports:
      - "6380:6379"
    volumes: 
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: