version: '3.8'
services: 
  redis: 
    image: redis:7-alpine
    container_name: exness_redis
    ports: 
      - 6382:6379
    volumes:
      - redis_data:/data
    command: redis-server --requirepass password --appendonly yes
    
volumes: 
  redis_data: